### ISSUE TITLE
Make downstream drivers component-able

### ISSUE THREAD

**Issue by esteve** [ros-drivers/transport_drivers#29]
It should be possible to create downstream drivers as components, i.e. registered in the component registry, no main function, etc.

This ticket is part of https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/277

**Comment by flynneva** [comment]
i think this can be closed, right @esteve @JWhitleyWork

**Comment by JWhitleyWork** [comment]
@flynneva Since UdpSocket is not dependent upon ROS directly, yes, it is possible for `udp_driver`. However, the way that `serial_driver` is currently written, it requires inheritence from a `SerialDriverNode` class which is ROS-dependent and has a `run` function which isn't started on construction. This makes it difficult to work with in a Component. If we update the structure of `serial_driver` to match that of `udp_driver`, then yes, this can be closed.

**Comment by flynneva** [comment]
@JWhitleyWork can this one be closed now?

**Comment by JWhitleyWork** [comment]
Yes. Closing.
