### ISSUE TITLE
update serial_driver and udp_driver binaries that are released

### ISSUE THREAD

**Issue by flynneva** [ros-drivers/transport_drivers#61]
the currently released [`serial_driver`](https://index.ros.org/p/serial_driver/github-ros-drivers-transport_drivers/#galactic) and [`udp_driver`](https://index.ros.org/p/udp_driver/github-ros-drivers-transport_drivers/#galactic)'s do not include executables or launch files and can only really be used within code.

could we tag and release both packages so we can push a new release? @JWhitleyWork @esteve

**Comment by JWhitleyWork** [comment]
Foxy version has been released as `1.0.0`. See https://github.com/ros/rosdistro/pull/30607
Will release for Galactic and Rolling once #57 is merged.

**Comment by JWhitleyWork** [comment]
Now released for Galactic too. See https://github.com/ros/rosdistro/pull/30608.

Couldn't release for Rolling at this time as there seems to be an issue with using the `udp_msgs` package (I think it's a Rolling-related bug). See the Actions for this repo with a recent Rolling build. The build will say it passed because I'm marking the build step as OK to fail but the error logs will show you the problem. Not sure how to fix it.
