### ISSUE TITLE
Warnings in console while not activated 

### ISSUE THREAD

**Issue by bondar000** [ros-drivers/transport_drivers#78]
1) Run remote udp sender
2) Run udp_receiver_node
3) Configure udp_receiver_node
Got multiple warning in console until not activated

`
[WARN] [1647610867.318857689] [LifecyclePublisher]: Trying to publish message on the topic 'udp_read', but the publisher is not activated
`

**Comment by JWhitleyWork** [comment]
@bondar000 This is because the node is a Lifecycle Node. It starts up in the Unconfigured state and needs to be manually transitioned through states. It needs to go from Unconfigured to Configured and then to Active. See https://index.ros.org/p/lifecycle/ for details on how to make the transitions with the `ros2 lifecycle` command.
