### ISSUE TITLE
UDP Bridge Node is not working

### ISSUE THREAD

**Issue by kkomurcu** [ros-drivers/transport_drivers#79]
Hello Community and @flynneva,
I have a problem while running the bridge node. I can see ip address and port but cannot see message in terminal after 
running this terminal code:
 
`ros2 run udp_driver udp_bridge_node_exe --ros-args --params-file ./src/transport_drivers/udp_driver/params/example_udp_params.yaml `

The figure about this problem is below. Can you help me about this?

![Screenshot from 2022-03-31 14-43-41](https://user-images.githubusercontent.com/102783752/161200288-3f50f9ee-c34c-4bcc-b189-28346e6bb8e8.png)

Pc: Msi gs66 stealth
Os: Ubuntu 20.04
Ros Distribution: Ros2 foxy

Thanks and regards.

**Comment by flynneva** [comment]
hi @kkomurcu, could you include a bit more in what is going wrong / what you are seeing?

The screenshot you included seems to be the normal output I think?

**Comment by Myung-Hyun** [comment]
I have same issue in my situation. I don't have any problem, I mean upb_bridege_node don't die, but the node don't publish any data even if packets is on the ethernet network. In my case, receiver_callback isn't call any time.

How can I do to solve this?? I wanna debugging method or some examples that run correctly

**Comment by flynneva** [comment]
@Myung-Hyun I'd recommend opening a new issue and linking to this one. Maybe try some of the following to debug:

1. Can you see the node in `rqt_graph` or `ros2 node list` CLI?
2. Does `ros2 topic echo` work for the topic you are publishing to?
3. Are you accidentally setting the `ROS_DOMAIN_ID` somehow, causing the nodes topic to be published to a different domain?

Any of those might point you to the issue...but its hard to debug with the info you provided. If you still have an issue, open a new issue and share more detailed info on exactly what the issue is and what you have tried to fix it 👍🏼
